server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/employees?characterEncoding=UTF-8
    username: root
    password: root

mybatis:
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    root: info

platform:
  date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8